---
conditions: v1
stages:
  - name: check
  - name: basic-tests
  - name: full-tests
    if: branch = master OR type = pull_request OR tag IS present
  - name: deploy
    if: tag IS present

sudo: required
dist: xenial
language: python

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip
    - .tox

services:
  - docker

jobs:
  fast_finish: true
  include:
    # Initial checks
    # Check basic py3 functionality and python 2 syntax via pyflakes
    - python: 2.7
      env: TOXENV=py27flakes TOXCFG=tox.ini
      stage: check
    - python: 3.7
      env: TOXENV=py37black TOXCFG=tox.ini
      stage: check
    - python: 3.7
      env: TOXENV=py37 TOXCFG=tox.ini
      stage: check
    - python: 3.7
      env: TOXENV=py36lint TOXCFG=tox.ini
      stage: check
    - python: 3.7
      env: TOXENV=py37isort TOXCFG=tox.ini
      stage: check

    # 'Basic' tests
    # Run more involved tests for python 2 and integration tests
    - python: 2.7
      env: TOXENV=py27 TOXCFG=tox.ini
      stage: basic-tests
    - python: 2.7
      env: TOXENV=py27lint TOXCFG=tox.ini
      stage: basic-tests

    - python: 2.7
      env: TOXENV=py27-generic TOXCFG=tox-integration.ini
      stage: basic-tests
    - python: 3.7
      env: TOXENV=py37-generic TOXCFG=tox-integration.ini
      stage: basic-tests

    # 'Full' tests
    # This runs for different versions of Python that we support as well as the
    # full integration test suite
    - python: 3.4
      env: TOXENV=py34 TOXCFG=tox.ini
      stage: full-tests
    - python: 3.5
      env: TOXENV=py35 TOXCFG=tox.ini
      stage: full-tests
    - python: 3.6
      env: TOXENV=py36 TOXCFG=tox.ini
      stage: full-tests
    # - python: pypy
    #   env: TOXENV=pypy TOXCFG=tox.ini
    #   stage: full-tests
    # - python: pypy3
    #   env: TOXENV=pypy3 TOXCFG=tox.ini
    #   stage: full-tests

    - python: 3.4
      env: TOXENV=py34-generic TOXCFG=tox-integration.ini
      stage: full-tests
    - python: 3.5
      env: TOXENV=py35-generic TOXCFG=tox-integration.ini
      stage: full-tests
    - python: 3.6
      env: TOXENV=py36-generic TOXCFG=tox-integration.ini
      stage: full-tests
    # - python: pypy
    #   env: TOXENV=pypy-generic TOXCFG=tox-integration.ini
    #   stage: full-tests
    # - python: pypy3
    #   env: TOXENV=pypy3-generic TOXCFG=tox-integration.ini
    #   stage: full-tests

    - python: 3.7
      env: TOXENV=py37-mqtt TOXCFG=tox-integration.ini
      stage: full-tests
    - python: 3.7
      env: TOXENV=py37-advanced TOXCFG=tox-integration.ini
      stage: full-tests
    - python: 3.7
      env: TOXENV=py37-hooks TOXCFG=tox-integration.ini
      stage: full-tests
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: michaelboulton
        password:
          secure: "OBnRGStdCmXpAIenI28wxhQ00R/2nUkxHxjpaCao4wa3+saTYQ9syobY4alSB6rdUmeemK8T/r14ikq1kmhX7aPTyrFbRMHCRfNqupU3GZox3pDsnQZd8B3ufBpda38i+OAk8z0FSrOAkH/cmODo13LljrELFh/5WDTjvqgZ0E3xosj+TgtAS2hCFZpI2dvlymd2lkC4RWE0GL4knq6pVsJELK2UrxQGEFTEv1oJeH61hecrCoJeCgo8E1iFo5yyn77Fp07rbLHXvK3gS6Nx/PkvAOQw8bUfmTP+V/8HkdG1ZHSzwUS9PCssQm6hlVy1Dh129Z395LjVV/q4MY7QtkKTSpIMoNkaaX1wLCWiVEItWzgpJQlosZ7BVh7GuWsXvLn0FgBjDB/e4CUJ8+NAzON438DcYrGrEcaYiVaxTvbwGolFIhgM+1x/LBgsjMXN9/ihuL+w1XSDwI9KV2W3SXtJOTVmFuPBzKkcR4eWn8cnjitbiXYQrXgj9QQFtGz8Hnm2T2Wp8hHYhHIPWVazrlSQA49GK5cxlF59xAc8ghTth9rzt0/7TOZoW9Y9YzfO5RyMZR+qcLeathQsqEeZtoYAvSWIOvt2uiu57hvlKONiWBuYLltHLov6OLs0MNJDdaiabQKvktjU8Nl5lDfIj6x59QXp5+ly7/DwG0gMwpc="
        on:
          tags: true

install:
  - pip install tox-travis setuptools --upgrade

# command to run tests
script:
  - tox -c ${TOXCFG}
