---
conditions: v1
stages:
  - name: basic-tests
  - name: full-tests
    if: branch = master OR type = pull_request OR tag IS present
  - name: deploy
    if: tag IS present

sudo: required
dist: xenial
language: python

branches:
  only:
    - master
    - staging
    - trying
    - /^\d+\.\d+\.\d+$/

cache:
  directories:
    - $HOME/.cache/pip
    - .tox

services:
  - docker

jobs:
  fast_finish: true
  include:
    # 'Basic' tests and checks
    # Pylint, formatting/sorting, and quickest unit/integration tests
    - python: 3.8
      env: TOXENV=py38black TOXCFG=tox.ini
      stage: basic-tests
    - python: 3.8
      env: TOXENV=py38 TOXCFG=tox.ini
      stage: basic-tests
    - python: 3.8
      env: TOXENV=py38lint TOXCFG=tox.ini
      stage: basic-tests
    - python: 3.8
      env: TOXENV=py38mypy TOXCFG=tox.ini
      stage: basic-tests
    - python: 3.8
      env: TOXENV=py38isort TOXCFG=tox.ini
      stage: basic-tests
    - python: 3.8
      env: TOXENV=py38-generic TOXCFG=tox-integration.ini
      stage: basic-tests

    # 'Full' tests
    # This runs for different versions of Python that we support as well as the
    # full integration test suite
    - python: 3.7
      env: TOXENV=py37-generic TOXCFG=tox-integration.ini
      stage: full-tests
    - python: pypy3
      env: TOXENV=pypy3-generic TOXCFG=tox-integration.ini
      stage: full-tests

    - python: 3.8
      env: TOXENV=py38-mqtt TOXCFG=tox-integration.ini
      stage: full-tests
    - python: 3.8
      env: TOXENV=py38-advanced TOXCFG=tox-integration.ini
      stage: full-tests
    - python: 3.8
      env: TOXENV=py38-hooks TOXCFG=tox-integration.ini
      stage: full-tests

    # deploy
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        edge: true
        user: michaelboulton
        distributions: bdist_wheel
        skip_existing: true
        password:
          secure: "M6S6aQ0+kVbOn/C7JgxJ6Nk4X4+HXuoOjcXAshG5oyJPlPBQxrDVPyjF2H0/ymbQFlz8HnDx959wNbYsDMrW0Od8A8HzWZaoyAqqbaLQ1i5XJ6X8XELSvAzoEcmpuLcnu+NoIiGjMNYg5OtnPGKlRekKS8t8y4xH9GPiz+3AFlH+lh/QkPuzSSukw14tyU8srHQ5cLNp1lXF6TFXPYCLf5JDW2KijUAV0HIx/MookYRv0U1EXhjRzd5MkIf8yn7Bvvg8d5Ns+3v4tV+syMQXBQf5BH/1925hJt2T9M26d0tUUMKVNJpqLTENr9J/p/b8OglQuFttscDxuBpnJyrmrPuUgKckHseHs+5X4g/s4uoxFQ3BKvVY5fHBdXTraZhWrKPo0rOY8ZAI31gdb/aZBWl5NqabkmOss5d0AfdU+CYpnLZDGOe+MghzPeojFYrdSwBaQ0QgyOV5VOc1s7UrzdSeCXANYmtMYGE/Abjw+XKy1cFpdxNHdJ4cZzS3SovykbU2iHYlO2OiWE69hJeId//bCddHSwLtqfTgqp7jG8kKnfBKNf1ew9Tw4uGeJcYr+XfSvlOhp3kG7U4F+AWhq78OKizkcgc+aP5sdyDqEILZ4KTlGNRw51msMAgwDTYrXAN0lJ5tGZoPpVn4pxWbu9rkacbxsbQg0b5rie+VlV8="
        on:
          tags: true

install:
  - pip install tox-travis setuptools --upgrade

# command to run tests
script:
  - tox -c ${TOXCFG}
