[project]
name = "my_tavern_plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.entry-points.tavern_file]
my_tavern_plugin = "my_tavern_plugin.plugin"