[project]
name = "custom-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[project.entry-points.tavern_file]
custom_backend = "custom_backend"